Repository VIT-Bhopal-AI-Innovators-Hub/Darzi-AI-Resume-Suite, pull requests merged in 2025-08, with the labels that each got.

#22 feat(auth): integrate Clerk (App Router) + protect dashboard
  README.md
  frontend/.env.example
  frontend/.gitignore
  frontend/README.md
  frontend/app/Dashboard/components/header.tsx
  frontend/app/Dashboard/page.tsx
  frontend/app/layout.tsx
  frontend/app/sign-in/[[...sign-in]]/page.tsx
  frontend/app/sign-up/[[...sign-up]]/page.tsx
  frontend/components/header.tsx
  frontend/middleware.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: enhancement

#33 Add Health Endpoints and Fix FastAPI Dependencies
  backend/api/main.py
  backend/api/pyproject.toml
  backend/api/requirements.txt
Labels: bug

#48 Added all tools for MCP and integrated LLM
  LICENSE
  backend/api/.env.example
  backend/api/Dockerfile
  backend/api/LICENSE
  backend/api/README.md
  backend/api/ats_test.json
  backend/api/main.py
  backend/api/pyproject.toml
  backend/api/requirements.txt
  backend/api/resume_test.txt
  backend/api/src/api/__init__.py
  backend/api/src/api/main.py
  backend/api/src/api/streamlit_app.py
  backend/api/src/app.py
  backend/api/src/streamlit_app.py
  backend/api/src/utils/__init__.py
  backend/api/src/utils/ats/__init__.py
  backend/api/src/utils/ats/analyzer.py
  backend/api/src/utils/data_extractor/__init__.py
  backend/api/src/utils/data_extractor/core.py
  backend/api/src/utils/data_extractor/utils.py
  backend/api/src/utils/llm/__init__.py
  backend/api/src/utils/llm/base.py
  backend/api/src/utils/llm/manager.py
  backend/api/src/utils/llm/providers/__init__.py
  backend/api/src/utils/llm/providers/gemini.py
  backend/api/src/utils/parser/__init__.py
  backend/api/src/utils/parser/core.py
  backend/api/src/utils/parser/enhanced.py
  backend/api/src/utils/parser/field_extractor.py
  backend/api/src/utils/resume_generator/__init__.py
  backend/api/src/utils/resume_generator/core.py
  backend/api/src/utils/resume_generator/templates.py
  backend/api/startup.sh
  backend/api/streamlit_app.py
  frontend/package.json
Labels: backend, priority: high 🔥, feature ✨
